<a href="https://colab.research.google.com/github/Netri-100224/Multiple_Disease_Prediction_System/blob/Disease_models/HeartDiseasePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install -U scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 29.8 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pickle

In [ ]:
df= pd.read_csv('/content/HeartDiseaseTrain-Test.csv')
df.head()

age     sex chest_pain_type  resting_blood_pressure  cholestoral  \
0   52    Male  Typical angina                     125          212   
1   53    Male  Typical angina                     140          203   
2   70    Male  Typical angina                     145          174   
3   61    Male  Typical angina                     148          203   
4   62  Female  Typical angina                     138          294   

      fasting_blood_sugar               rest_ecg  Max_heart_rate  \
0    Lower than 120 mg/ml  ST-T wave abnormality             168   
1  Greater than 120 mg/ml                 Normal             155   
2    Lower than 120 mg/ml  ST-T wave abnormality             125   
3    Lower than 120 mg/ml  ST-T wave abnormality             161   
4  Greater than 120 mg/ml  ST-T wave abnormality             106   

  exercise_induced_angina  oldpeak        slope vessels_colored_by_flourosopy  \
0                      No      1.0  Downsloping                           Two   
1                     Yes      3.1    Upsloping                          Zero   
2                     Yes      2.6    Upsloping                          Zero   
3                      No      0.0  Downsloping                           One   
4                      No      1.9         Flat                         Three   

         thalassemia  target  
0  Reversable Defect       0  
1  Reversable Defect       0  
2  Reversable Defect       0  
3  Reversable Defect       0  
4       Fixed Defect       0

In [ ]:
df.shape

(1025, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   age                            1025 non-null   int64  
 1   sex                            1025 non-null   object 
 2   chest_pain_type                1025 non-null   object 
 3   resting_blood_pressure         1025 non-null   int64  
 4   cholestoral                    1025 non-null   int64  
 5   fasting_blood_sugar            1025 non-null   object 
 6   rest_ecg                       1025 non-null   object 
 7   Max_heart_rate                 1025 non-null   int64  
 8   exercise_induced_angina        1025 non-null   object 
 9   oldpeak                        1025 non-null   float64
 10  slope                          1025 non-null   object 
 11  vessels_colored_by_flourosopy  1025 non-null   object 
 12  thalassemia                    1025 non-null   o

In [ ]:
from sklearn import preprocessing

# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
df['sex']= label_encoder.fit_transform(df['sex'])
df['sex'].unique()


array([1, 0])

In [ ]:
df['chest_pain_type']= label_encoder.fit_transform(df['chest_pain_type'])
df['chest_pain_type'].unique()

array([3, 1, 2, 0])

In [ ]:
df['fasting_blood_sugar']= df['fasting_blood_sugar'].str.replace('Lower than 120 mg/ml','0')
df['fasting_blood_sugar']= df['fasting_blood_sugar'].str.replace('Greater than 120 mg/ml','1')
df['fasting_blood_sugar'].unique()

array(['0', '1'], dtype=object)

In [ ]:

df['rest_ecg']=df['rest_ecg'].str.replace('Normal','0')
df['rest_ecg']=df['rest_ecg'].str.replace('ST-T wave abnormality','1')

df['rest_ecg']=df['rest_ecg'].str.replace('Left ventricular hypertrophy','2')

df['rest_ecg'].unique()

array(['1', '0', '2'], dtype=object)

In [ ]:
df['exercise_induced_angina']= label_encoder.fit_transform(df['exercise_induced_angina'])
df['exercise_induced_angina'].unique()

array([0, 1])

In [ ]:

df['slope']=df['slope'].str.replace('Flat','0')
df['slope']=df['slope'].str.replace('Upsloping','1')



df['slope']=df['slope'].str.replace('Downsloping','2')
df['slope'].unique()

array(['2', '1', '0'], dtype=object)

In [ ]:
df['vessels_colored_by_flourosopy']= label_encoder.fit_transform(df['vessels_colored_by_flourosopy'])
df['vessels_colored_by_flourosopy'].unique()

array([3, 4, 1, 2, 0])

In [ ]:
df['thalassemia']= label_encoder.fit_transform(df['thalassemia'])

df['thalassemia'].unique()


array([3, 0, 2, 1])

In [ ]:
df.isnull().sum()

age                              0
sex                              0
chest_pain_type                  0
resting_blood_pressure           0
cholestoral                      0
fasting_blood_sugar              0
rest_ecg                         0
Max_heart_rate                   0
exercise_induced_angina          0
oldpeak                          0
slope                            0
vessels_colored_by_flourosopy    0
thalassemia                      0
target                           0
dtype: int64

In [ ]:
df.describe()

age          sex  chest_pain_type  resting_blood_pressure  \
count  1025.000000  1025.000000      1025.000000             1025.000000   
mean     54.434146     0.695610         2.171707              131.611707   
std       9.072290     0.460373         0.959013               17.516718   
min      29.000000     0.000000         0.000000               94.000000   
25%      48.000000     0.000000         2.000000              120.000000   
50%      56.000000     1.000000         2.000000              130.000000   
75%      61.000000     1.000000         3.000000              140.000000   
max      77.000000     1.000000         3.000000              200.000000   

       cholestoral  Max_heart_rate  exercise_induced_angina      oldpeak  \
count   1025.00000     1025.000000              1025.000000  1025.000000   
mean     246.00000      149.114146                 0.336585     1.071512   
std       51.59251       23.005724                 0.472772     1.175053   
min      126.00000       71.000000                 0.000000     0.000000   
25%      211.00000      132.000000                 0.000000     0.000000   
50%      240.00000      152.000000                 0.000000     0.800000   
75%      275.00000      166.000000                 1.000000     1.800000   
max      564.00000      202.000000                 1.000000     6.200000   

       vessels_colored_by_flourosopy  thalassemia       target  
count                    1025.000000  1025.000000  1025.000000  
mean                        3.002927     1.331707     0.513171  
std                         1.293384     1.444014     0.500070  
min                         0.000000     0.000000     0.000000  
25%                         2.000000     0.000000     0.000000  
50%                         4.000000     0.000000     1.000000  
75%                         4.000000     3.000000     1.000000  
max                         4.000000     3.000000     1.000000

In [ ]:
df['target'].value_counts()

1    526
0    499
Name: target, dtype: int64

1=Heart disease,

0=No disease


In [ ]:
x = df.drop(columns='target',axis=1)
y = df['target']

In [ ]:
print(x)

      age  sex  chest_pain_type  resting_blood_pressure  cholestoral  \
0      52    1                3                     125          212   
1      53    1                3                     140          203   
2      70    1                3                     145          174   
3      61    1                3                     148          203   
4      62    0                3                     138          294   
...   ...  ...              ...                     ...          ...   
1020   59    1                1                     140          221   
1021   60    1                3                     125          258   
1022   47    1                3                     110          275   
1023   50    0                3                     110          254   
1024   54    1                3                     120          188   

     fasting_blood_sugar rest_ecg  Max_heart_rate  exercise_induced_angina  \
0                      0        1             168        

In [ ]:
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64


Splitting into test train data

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [ ]:
print(x_train.shape,x_test.shape)

(820, 13) (205, 13)


In [ ]:
model=LogisticRegression()
model.fit(x_train,y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
train_pred=model.predict(x_train)
train_acc=accuracy_score(train_pred,y_train)
print('accuracy',train_acc)

accuracy 0.8475609756097561


In [ ]:
test_pred=model.predict(x_test)
test_acc=accuracy_score(test_pred,y_test)
print('accuracy',test_acc)

accuracy 0.8097560975609757


Build a predictive system

In [ ]:
df.head()

age  sex  chest_pain_type  resting_blood_pressure  cholestoral  \
0   52    1                3                     125          212   
1   53    1                3                     140          203   
2   70    1                3                     145          174   
3   61    1                3                     148          203   
4   62    0                3                     138          294   

  fasting_blood_sugar rest_ecg  Max_heart_rate  exercise_induced_angina  \
0                   0        1             168                        0   
1                   1        0             155                        1   
2                   0        1             125                        1   
3                   0        1             161                        0   
4                   1        1             106                        0   

   oldpeak slope  vessels_colored_by_flourosopy  thalassemia  target  
0      1.0     2                              3            3       0  
1      3.1     1                              4            3       0  
2      2.6     1                              4            3       0  
3      0.0     2                              1            3       0  
4      1.9     0                              2            0       0

In [ ]:
df.tail()

age  sex  chest_pain_type  resting_blood_pressure  cholestoral  \
1020   59    1                1                     140          221   
1021   60    1                3                     125          258   
1022   47    1                3                     110          275   
1023   50    0                3                     110          254   
1024   54    1                3                     120          188   

     fasting_blood_sugar rest_ecg  Max_heart_rate  exercise_induced_angina  \
1020                   0        1             164                        1   
1021                   0        0             141                        1   
1022                   0        0             118                        1   
1023                   0        0             159                        0   
1024                   0        1             113                        0   

      oldpeak slope  vessels_colored_by_flourosopy  thalassemia  target  
1020      0.0     2                              4            0       1  
1021      2.8     0                              1            3       0  
1022      1.0     0                              1            0       0  
1023      0.0     2                              4            0       1  
1024      1.4     0                              1            3       0

In [ ]:
filename='heart_disease_model.sav'
pickle.dump(model,open(filename,'wb'))
loaded_model=pickle.load(open(filename,'rb'))

In [ ]:
inp=(59,1,1,140,221,0,1,164,1,0.0,2,4,0)
dataas_array=np.asarray(inp)
data_reshaped=dataas_array.reshape(1,-1)
pred=model.predict(data_reshaped)
print(pred)
if (pred[0]== 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

[1]
The Person has Heart Disease


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
